package com.ppwallet.rules;

public class RulesFactoryImpl implements RulesFactory{
	
	private Rules rules;

	@Override
	public Rules createRule(String ruleName) throws Exception {
		
		switch(ruleName){
		case Rules.DEFAULT_LOGIN_MODULE: case Rules.LOGIN_VALIDATE: case Rules.LOGOUT_MODULE: case Rules.PROFILE_USER_DASHBOARD: case Rules.PROFILE_USER_VIEWPROFILE: 
	    case Rules.PROFILE_USER_EDITPROFILE_UPDATE: case Rules.JSON_OPS_LOGIN_VALIDATE:
		case Rules.JSON_CUST_LOGIN_VALIDATE: case Rules.JSON_GET_KEY:case Rules.PROFILE_USER_REGISTER_BANKPAGE: case Rules.PROFILE_REGISTERBANK_DETAILS: case Rules.PROFILE_USER_REGISTER_MPESAPAGE: case Rules.PROFILE_USER_REGISTER_MPESANUMBER: 
			rules = new UserProfileRulesImpl();
		break;
		 
		case Rules.WALLET_VIEW_WALLET_PAGE: case Rules.WALLET_TOPUP_WALLET_WELCOMEPAGE: case Rules.WALLET_TOPUP_BY_BANK:  case Rules.WALLET_TOPUP_BY_MPESA:
		case Rules.WALLET_SHOWUSER_TXN_ALLWALLETS_PAGE: case Rules.WALLET_SHOW_INDIVIDUAL_TRANSACTIONS: case Rules.WALLET_TRANSFER_FUND_PAGE: 
		case Rules.WALLET_SEND_MONEY_PAGE:   case Rules.WALLET_SEND_MONEY_REGISTER_RECEIVERPAGE: case Rules.WALLET_P2P_REG_WALLET:  case Rules.WALLET_P2P_REG_SEARCH_WALLET:
		case Rules.WALLET_P2P_REG_RECEIVER_WALLETID_REGISTER: case Rules.TOPUP_WITHCARD:
			
			//case WALLET_TOPUP_WALLET_WITH_WALLETID_PAGE: case WALLET_REGISTER_NEW_WALLET: case WALLET_JSON_GETLASTTEST_TXN: 
		//case WALLET_SHOWUSER_TXN_ALLWALLETS: case WALLET_SHOWUSER_TXN_ALLWALLETS_PAGE: case WALLET_WITHDRAW_CASH_PAGE: case WALLET_CASHWITHDRAW_GENERATE_QRCODE:
		//case WALLET_CUSTOMER_CASHWITHDRAW:
			//Mobile
		case Rules.JSON_WALLET_VIEW_WALLET_PAGE: case Rules.JSON_WALLET_SHOWUSER_TXN_ALLWALLETS_PAGE: case Rules.JSON_WALLET_SHOWUSER_TXN_INDIVIDUALWALLETS_PAGE: case Rules.JSON_WALLET_SHOWUSER_TXN_INDIVIDUALWALLETS: case Rules.JSON_WALLET_TOPUP_WALLET_WELCOMEPAGE: case Rules.JSON_WALLET_TOPUP_BY_BANK:case Rules.JSON_WALLET_TOPUP_BY_MPESA: case Rules.JSON_WALLET_TRANSFER_FUND_PAGE:
		case Rules.JSON_WALLET_SEND_FUNDS: case Rules.JSON_WALLET_P2P_REG_SEARCH_WALLET: case Rules.JSON_WALLET_P2P_REG_RECEIVER_WALLETID_REGISTER: case Rules.JSON_USER_REGISTER_BANKPAGE: case Rules.JSON_REGISTERBANK_DETAILS: case Rules.JSON_REGISTER_MPESAPAGE: 
			case Rules.JSON_REGISTER_MPESANUMBER: case Rules.JSON_WALLET_SHOWUSER_TXN_INDIVIDUALWALLETS_GRAPH:
				
			case Rules.JSON_CUST_GET_WALLET_DETAILS: case Rules.JSON_CUST_WALLET_TOPUP_WITH_QR: case Rules.JSON_CUST_WALLET_CASHOUT_WITH_QR:
			rules = new WalletRulesImpl();
		break;
		case Rules.BATCH_PROCES_PAGE:
			rules = new BatchProcessRulesImpl();
		break;
		
		case Rules.CUST_VIEW_REWARDS_PAGE: case Rules.CUST_CLAIM_REWARDS_PAGE: case Rules.CUST_VIEW_REWARDS_RULES_PAGE: case Rules.CUST_CLAIM_EACH_REWARD: case Rules.CUST_DISPLAY_SELECTED_WALLETPOINTS:  case Rules.CUST_CLAIM_ALL_REWARD:
		case Rules.JSON_CUST_VIEW_REWARDS_RULES: case Rules.JSON_CUST_VIEW_REWARDS_PAGE: case Rules.JSON_CUST_CLAIM_EACH_REWARD: case Rules.JSON_CUST_CLAIM_ALL_REWARD:
			rules = new LoyaltyRulesImpl();
		break;
		case Rules.PAYMENT_BILL_PAYPAGE:  case Rules.PAYMENT_BILLPAY_REG_NEW_BILLER_PAGE: case Rules.PAYMENT_BILLPAY_BILLER_NEWREGISTER_PAGE:  case Rules.PAYMENT_BILLPAY_BILLPAYRREQ:   
		case Rules.PAYMENT_BILLPAY_REQCONFIRM: case Rules.PAYMENT_BILLPAY_SHOW_BILLERS:case Rules.PAYBILL_WITHCARD: case Rules.PAYMENT_CARDS_SHOWALLCARDS_USER:
			//Mobile
		case Rules.JSON_PAYMENT_BILL_PAYPAGE: case Rules.JSON_PAYMENT_BILLPAY_REG_NEW_BILLER_PAGE:case Rules.JSON_PAYMENT_BILLPAY_BILLER_NEWREGISTER_PAGE:case Rules.JSON_PAYMENT_BILLPAY_BILLPAYRREQ:
		case Rules.JSON_PAYMENT_BILLPAY_PAYNOW: case Rules.JSON_PAYMENT_VIEW_PAYBILL_TXN: case Rules.JSON_PAYMENT_VIEW_PAYBILL_TXN_GRAPH:
			
		case Rules.JSON_CUST_RETAIL_PAYMENT: case Rules.JSON_CUST_RETAIL_PAYMENT_TABLE: case Rules.JSON_CUST_RETAIL_PAYMENT_GRAPH: case Rules.CARD_REGISTRATION_PAGE: case Rules.PAYMENT_REGISTER_NEW_CARD_REQ:
			rules = new PaymentRulesImpl();
			break;

			
			//new Stuff
	case Rules.CUST_RAISE_DISPUTE: case Rules.CUST_ADD_NEW_DISPUTE: case Rules.CUST_VIEW_DISPUTE: case Rules.CUST_SHOW_SPECIFIC_DISPUTE_PAGE: case Rules.CUST_ADD_COMMENT_FOR_A_DISPUTE: case Rules.CUST_UPDATE_DISPUTE_STATUS:
			
		case Rules.JSON_CUST_RAISE_DISPUTE: case Rules.JSON_CUST_ADD_NEW_DISPUTE: case Rules.JSON_CUST_VIEW_DISPUTE: case Rules.JSON_CUST_SHOW_SPECIFIC_DISPUTE_PAGE: case Rules.JSON_CUST_ADD_COMMENT_FOR_A_DISPUTE: case Rules.JSON_CUST_UPDATE_DISPUTE_STATUS:
			rules= new CustDisputeRulesImpl();
			break;
		
    
		case Rules.JSON_CUST_VIEW_PROFILE: case Rules.JSON_CUST_UPDATE_PROFILE: case Rules.CUST_SELF_REGISTRATION: case Rules.JSON_CUST_REGISTRATION: case Rules.PERSO_CUST_REGISTRATION:case Rules.JSON_PERSO_CUST_REGISTRATION:
			rules = new CustomerRulesImpl();
			break;
		
			/* Merchant related items */
		case Rules.DISP_MERCH_QR_CODE: case Rules.GET_MERCH_DETAILS:  case Rules.MERCH_PAYMENT_MODULE_DQR_PAGE: case Rules.MERCH_PAYMENTS_MODULE_QRPAGE:
		case Rules.MERCHANT_PAYMENT_MODULE_RETAIL_PAYMENT_PAGE: case Rules.MERCHANT_PAYMENT_MODULE_CASHOUT_PAGE: case Rules.MERCH_PAYMENT_MODULE_DYNAMICQR:
		case Rules.MERCH_PAYMENT_MODULE_RETAIL_PAYMENTSQR: case Rules.MERCH_PAYMENT_MODULE_CASHOUT: case Rules.MERCHANT_PAYMENT_MODULE_TOPUP_PAGE:
		case Rules.MERCHANT_PAYMENT_MODULE_TOPUPQR: case Rules.MERCHANT_BILLPAYMENT_MODULE_BILLER_DETAILS_PAGE:  case Rules.MERCHANT_BILLPAYMENT_TRANSACTIONS:
		//case Rules.MERCHANT_STATIC_QR_PAGE:
			//merch retro
			
		case Rules.REGISTRATION_REQ_PAGE: case Rules.REGISTRATION_MERCHANT_ADD: case Rules.MERCHANT_VIEW_PROFILE_PAGE: case Rules.MERCHANT_DOWNLOAD_KYC_DOC:
		case Rules.MERCHANT_UPDATE_PROFILE: case Rules.MERCHANT_VIEW_MSF:
			 rules = new MerchantRulesImpl() ;
		break;
		
		/*********Transactions*********/
		case Rules.MERCHANT_TOPUP_TRANSACTIONS_PAGE:  case Rules.MERCHANT_CASHOUT_TRANSACTIONS_PAGE:  case Rules.MERCHANT_RETAIL_TRANSACTIONS_PAGE: 
			rules = new MerchantTransactionsRulesImp();
			break;
		
		
		
		case Rules.JSON_MERCHANT_MOBILE_RETAIL_PAYMENT: case Rules.JSON_MERCHANT_MOBILE_CASHOUT_PAYMENT: case Rules.JSON_MERCHANT_MOBILE_TOPUP_PAYMENT: case Rules.JSON_MERCHANT_MOBILE_BILLER_DETAILS:
		case Rules.JSON_MERCHANT_MOBILE_BILLPAY_TXN_DETAILS: case Rules.JSON_MERCHANT_MOBILE_MCC_GROUP: case Rules.JSON_MERCHANT_MOBILE_SELF_REGISTRATION:
			
			rules = new MerchMobileRuleImpl();
		break; 
		
		/*Merchant mobile profile stuff*/
		case Rules.JSON_MERCHANT_MOBILE_VIEW_MERCHANT_PRF: case Rules.JSON_MERCHANT_MOBILE_EDIT_PERSONAL_PRF:  case Rules.JSON_MERCHANT_MOBILE_EDIT_CONTACT_PRF:
		case Rules.JSON_MERCHANT_MOBILE_EDIT_COMPANY_PRF: case Rules.JSON_MERCHANT_MOBILE_DOWNLOAD_KYC_DOCS:
			
			rules = new MerchMobileProfileRuleImpl();
		break;
		
		/*Merchant disputes module*/
		case Rules.JSON_MERCHANT_MOBILE_SHOW_DISPUTE_REASONS:  case Rules.JSON_MERCHANT_MOBILE_RAISE_DISPUTES: case Rules.JSON_MERCHANT_MOBILE_VIEW_DISPUTE: 
		case Rules.JSON_MERCH_MOBILE_SHOW_SPECIFIC_DISPUTE_PAGE: case Rules.JSON_MERCH_MOBILE_ADD_COMMENT_FOR_A_DISPUTE:
			/*Merch web dispute*/
		case Rules.MERCHANT_VIEW_DISPUTE:  case Rules.MERCHANT_RAISE_DISPUTE:  case Rules.MERCHANT_ADD_NEW_DISPUTE: case Rules.MERCHANT_SHOW_SPECIFIC_DISPUTE_PAGE:
		case Rules.MERCHANT_ADD_COMMENT_FOR_A_DISPUTE: case Rules.MERCHANT_UPDATE_DISPUTE_STATUS:
			rules = new MerchDisputeRulesImp();
			break;
			
			
		case Rules.JSON_MERCHANT_MOBILE_VIEW_MSF_PLAN:case Rules.JSON_MERCHANT_MOBILE_VIEW_TRANSACTIONS:
			rules = new MerchMsfPlanRulesImp();

			break;
			
			/*==================================Operations Rules==============================*/
			
			
			
			
		case Rules.OPS_SYS_CARDS_ADD_NEW_BIN: case Rules.OPS_SYS_CARDS_UPDATECARDSBIN:	case Rules.OPS_SYS_CARDS_VIEWALL_BIN_PAGE: case Rules.OPS_SYS_CARDS_VIEWALLPRODUCT_PAGE:
		case Rules.OPS_SYS_CARDS_EDITSPECPRODUCT: case Rules.OPS_SYS_CARDS_CREATECARDPRODUCT:
			rules = new OpsSystemSetupCardsRulesImpl();
		break;
		
		case Rules.OPS_SYS_MERCH_MCCMANAGE_PAGE: case Rules.OPS_SYS_MERCH_EDITMCC: case Rules.OPS_SYS_MERCH_ADDMCC: 
		case Rules.OPS_SYS_MERCH_INST_CREATE_NEW_PAGE: 

		case Rules.OPS_SYS_MERCH_EDIT_INST: case Rules.OPS_SYS_MERCH_SETMSFPLAN_PAGE: case Rules.OPS_SYS_MERCH_ADD_MSFPLAN: case Rules.OPS_SYS_MERCH_EDIT_MSFPLAN:
		case Rules.OPS_SYS_MERCH_VIEW_MSF:	case Rules.OPS_MERCH_ALLOCATE_MSF_PLANS: case Rules.OPS_MERCH_UPDATE_PLANSTATUS_FOR_BILLER:
			
		case Rules.OPS_MERCH_VIEW_MERCH_DISPUTE_PAGE: case Rules.OPS_RAISE_DISPUTE_PAGE: 
		case Rules.OPS_MERCH_DISPUTE_REASONS_ADD: case Rules.OPS_MERCH_DISPUTE_REASONS_EDIT: case Rules.OPS_MERCH_DISPUTE_REASONS_PAGE: //case Rules.OPS_MERCH_ADDNEW_DISPUTE_MERCHANT:
		case Rules.OPS_MERCH_RAISE_MERCHANT_DISPUTE_PAGE: case Rules.OPS_EDIT_DISPUTE_PAGE: case Rules.OPS_VIEW_SPECIFIC_PAGE: case Rules.OPS_UPDATE_DISPUTE_STATUS: case Rules.OPS_ADD_DISPUTE_COMMENT:
			rules = new OpsSystemSetupMerchantRulesImpl();
		break; 
		
		case Rules.OPS_MERCH_SET_MERCHANTS_PAGE:	case Rules.OPS_MERCHANT_EDIT:
			case Rules.JSON_OPS_MERCH_GETSPCMERCH:  case Rules.OPS_MERCH_VIEW_CALL_LOGS: case Rules.OPS_MERCH_ADD_CALL_LOGS:
		case Rules.OPS_MERCH_VIEW_PENDING_MERCHANTS_PAGE:	case Rules.OPS_MERCH_VERIFY_PENDING_MERCHANTS: case Rules.OPS_MERCH_SHOWSPECIFIC_MERCH_PAGE:
		case Rules.OPS_MERCH_ADD_MERCHANTS_PAGE: case Rules.OPS_MERCH_EDITSPECIFIC_MERCH_PAGE:
		case Rules.OPS_MERCH_ADD_MERCHANT_PAGE:		case Rules.OPS_REGISTRATION_MERCHANT_ADD: case Rules.OPS_MERCHANT_DOWNLOAD_KYC_DOC:
		// case Rules.MERCHANT_UPDATE_PROFILE:
			rules = new OpsMerchantManageRulesImpl();
		break;
		
		case Rules.OPS_CUST_VIEW_CARD_DISPUTES_PAGE:case Rules.OPS_CUST_VIEW_CARDS_PAGE: case Rules.OPS_CUST_VIEW_PENDING_CUSTOMERS: case Rules.OPS_CUST_VERIFY_PENDING_CUSTOMERS: 
		case Rules.OPS_CUST_VIEW_CUSTOMERS_PAGE:	case Rules.OPS_CUST_WALLETS_PAGE:	case Rules.OPS_CUST_EDIT_CUSTDETAILS_PAGE:
		case Rules.OPS_CUST_SHOW_EACH_DISPUTE_PAGE: case Rules.OPS_CUST_UPDATE_DISPUTE_STATUS: case Rules.OPS_CUST_RAISE_CUST_DISPUTE_PAGE: case Rules.OPS_VIEW_RAISE_CUST_DISPUTE_PAGE:
		case Rules.OPS_CUST_VIEW_CALL_LOGS_PAGE: case Rules.OPS_CUST_SHOW_WALLETS_FOR_A_CUSTOMER:  case Rules.JSON_OPS_CUST_GETLASTHUNDRED_TXNS_FORWALLET:
		case Rules.OPS_CUST_ADD_CALL_LOGS:
			rules = new OpsCustomerManageRulesImpl();
		break;
		
		case Rules.OPS_VIEW_PROFILE_PAGE:  case Rules.OPS_ADMIN_UPDATE_PROFILE: case Rules.OPS_MANAGE_OPS_USER_PAGE:  case Rules.OPS_ADD_OPS_USER:  case Rules.OPS_EDIT_OPS_USER:
			rules = new OpsProfileRulesImpl();
			
		break;
		
		//do the rule for the page
		case Rules.OPS_VIEW_LOYALTY_RULES_PAGE:	case Rules.OPS_ADD_LOYALTY_RULE: case Rules.OPS_EDIT_LOYALTY_RULE: case Rules.OPS_VIEW_CUSTOMER_LOYALTY_PAGE:
		case Rules.OPS_VIEW_CUSTOMER_LOYALTY_CLAIM_PAGE:	case Rules.OPS_CUST_CLAIM_ALL_REWARD:
			rules = new OpsLoyaltyRulesImpl();	
			break;

			
		case Rules.OPS_VIEW_TRANSACTIONS_PAGE:  
			rules= new OpsTransactionsRulesImpl();
			break;
			
			
		case Rules.OPS_VIEW_AUDIT_TRAIL_PAGE:
			rules= new OpsAuditTrailManageRulesImpl();
			break;
			
			
			
			
			
			
		
		/*
		case WALLET_VIEW_WALLET_PAGE: case WALLET_TOPUP_WALLET_PAGE: case WALLET_TOPUP_WALLET_WITH_WALLETID_PAGE: case WALLET_REGISTER_NEW_WALLET: case WALLET_JSON_GETLASTTEST_TXN: 
		case WALLET_SHOWUSER_TXN_ALLWALLETS: case WALLET_SHOWUSER_TXN_ALLWALLETS_PAGE: case WALLET_WITHDRAW_CASH_PAGE: case WALLET_CASHWITHDRAW_GENERATE_QRCODE:
		case WALLET_CUSTOMER_CASHWITHDRAW:
			rules = new WalletRulesImpl();
		break;
		case PAYMENT_REGISTER_NEW_CARD_PAGE: case PAYMENT_REGISTER_NEW_CARD_REQ: case PAYMENT_TOPUP_WALLET_BYCARD:	case PAYMENT_BILLPAY_WELCOME_PAGE: 
		case PAYMENT_BILLPAY_ALLREG_BILLERS: case PAYMENT_BILLPAY_UPDATE_BILLER: case PAYMENT_BILLPAY_REG_NEW_BILLER_PAGE: case PAYMENT_BILLPAY_REG_NEW_BILLERREQ:
		case PAYMENT_BILLPAY_BILLPAY_REQ: case PAYMENT_BILLPAY_BILLPAY_REQCONFIRM: case PAYMENT_P2P_SEND_MONEY: case PAYMENT_P2P_WALLET_SENDMONEY:
		case PAYMENT_P2P_TOKEN_SENDMONEY: case PAYMENT_CARDS_SHOWALLCARDS_USER: case PAYMENT_BILLPAY_SHOWUSERTXNS: case PAYMENT_CARDS_VIEWTXNS: case PAYMENT_BILLPAY_SHOWUSERTXNS_PAGE:
		case PAYMENT_CARDS_VIEWTXNS_PAGE:
			rules = new PaymentRulesImpl();
		break;
		case PAYMENT_REWARDS_VIEW_LOYATLTYPOINTS: case PAYMENT_REWARDS_VIEW_LOYATLTYRULES: case PAYMENT_REWARDS_CLAIMPOINTS_PAGE:
			rules = new LoyaltyRulesImpl();
		break;
		case PAYMENT_MKTPLACE_VIEW_ALLPRODUCTS_BYUSER: case PAYMENT_MKTPLACE_SHOW_PARTCULAR_PRODUCT: case PAYMENT_MKTPLACE_PRODUCT_SAVESTATUS:
		case PAYMENT_MKTPLACE_PRODUCT_CREATENEWPAGE: case PAYMENT_MKTPLACE_SHOP_ALLPRODUCTS_VIEW: case PAYMENT_MKTPLACE_SHOP_VIEW_SPEC_GOODS: case PAYMENT_MKTPLACE_SHOP_ADD_TO_CARD:
		case PAYMENT_MKTPLACE_SHOP_REMOVECART: case PAYMENT_MKTPLACE_SHOP_CHECKOUT: case PAYMENT_MKTPLACE_PRODUCT_CREATENEW: case PAYMENT_MKTPLACE_SHOWUSERCART:
		case PAYMENT_MKTPLACE_PLACETXNORDER_BYWALLET: case PAYMENT_MKTPLACE_PLACETXNORDER_BYTOKEN: case PAYMENT_MKTPLACE_VIEWALLORDERS: case PAYMENT_MKTPLACE_VIEWALLORDERS_PAGE:
		case PAYMENT_MKTPLACE_SHOWUSERCART_PAGE: case PAYMENT_MKTPLACE_PRODUCT_CREATENEW_PAGE:
			rules = new MarketplaceRulesImpl();
		break;
		case OPN_VIEW_USERS_DEFAULT: case OPN_UPDATE_CUST_ACCESS: case OPN_ADD_USER_CUSTOMER_PAGE: case OPN_ADD_USER_MERCHANT_PAGE: case OPN_ADD_USER_OPERATION_PAGE:
		case OPN_ADD_USER_CUSTOMER:  case OPN_ADD_USER_MERCHANT: case OPN_ADD_USER_OPERATION: case OPN_GETUSERTYPES:
			rules = new OperationsRulesImpl();
		break;*/
		
		default: throw new Exception ("rule not defined");
			
		}
		
		
		return this.rules;
	}

}
